version: "3.8"
services:
  app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/youtube-ts
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    image: app:react
    container_name: react_container
    command: npm start
